### ISSUE TITLE
Share a published Graph by Email (with Mozilla)

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#123] opened 2021-06-08 10:03 UTC
Share a published Graph by Email doesn't work with Mozilla
![image](https://user-images.githubusercontent.com/79834090/121166380-4e824b00-c851-11eb-83aa-5d946f37fe9b.png)

**Comment by herrstucki** [comment] 2021-06-23 15:58
I can't reproduce this bug, it should work fine with Firefox. Maybe on your particular system no email client is available to Firefox? …

To double-check: does the email link on https://github.com/visualize-admin work?

I'm closing this issue. Feel free to re-open it if this is actually a problem that doesn't affect _all_ other email links.

**Closed** 2021-06-23 15:58 UTC
Labels: bug
