### ISSUE TITLE
Text can only be seen half

### ISSUE THREAD

**Issue by LiamBAFU** [visualize-admin/visualization-tool#1187] opened 2023-09-22 11:40 UTC
**Describe the bug**
The Text on the Horizontal axis can only be seen half. I think it has something to do with that some of  the numbers are going below zero and i think it can't handle that (but im not sure).

**To Reproduce**

1. Go to: https://int.[visualize.admin.ch](https://int.visualize.admin.ch/en/v/30rJtkSYetCW?dataSource=Prod)/en/v/30rJtkSYetCW?dataSource=Prod

(https://int.[visualize.admin.ch](https://int.visualize.admin.ch/en/v/30rJtkSYetCW?dataSource=Prod)/en/v/30rJtkSYetCW?dataSource=Prod)

2. The text on the horizontal axis is only half visible.

**Expected behavior**
You should see the whole Text

**Screenshots or video**
![22-09-2023_12-31-36](https://github.com/visualize-admin/visualization-tool/assets/145760304/f7572dd6-8e68-4d74-b070-63e0786f0093)

**Environment (please complete the following information):**

- Visualize environment and version: [e.g. INT v3.22.7 ]
- Browser and version [Microsoft Edge]

**Comment by bprusinowski** [comment] 2023-09-22 13:25
Hi @LiamBAFU, thanks for reporting the bug!

Could you provide more information on your environment (browser version, zoom level, operating system)? I wasn't able to reproduce the issue on Safari and Edge on MacOS and Edge 117.0.2045.31 (64 bit) on Windows 11.

While looking at this issue, I've noticed that the color legend in the shared chart is missing. Do you remember the steps you made to make the chart? It's broken when copying the chart, but I couldn't reproduce this either when making the chart from scratch.

I will be grateful for any insights!

**Comment by LiamBAFU** [comment] 2023-09-22 13:44
Hi @bprusinowski 

I'm using Microsoft Edge Version 117.0.2045.31

The weird thing is that i also don't have the problem anymore. I did not change anything to the last time but it's showing the whole text for me too now.

I can't tell you the steps how the chart was made since I wasn't the one that created it.
I'm gonna ask the person who created the chart if she can tell me how she created it.

**Comment by ortnever** [comment] 2023-09-25 07:01
Hi Bartosz and Liam,
As I displayed the chart this morning everything was ok. I cannot explain why we had the problem on Friday and how I made the chart.
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/7360f804-91f2-4464-8cdf-1dbc211f2159)

**Comment by bprusinowski** [comment] 2023-09-26 13:09
Hi, thanks for checking the chart again. I'll close the issue in this case, please feel free to re-open if the problem can be replicated in the future 👍

**Closed by bprusinowski** 2023-09-26 13:09 UTC
Labels: bug
