### ISSUE TITLE
Dimension Type not interpreted correctly

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#92] opened 2021-05-27 10:35 UTC
I entered a Dimension Typ "Key Dimension" for my dimension "Unit exposed to noise" in the cube-creator but it isn't interpreted correctly in Visualize (Filter is optional)
https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!testub001-mbbjkbnrab/metadata
![image](https://user-images.githubusercontent.com/79834090/119811354-4b996900-bee7-11eb-8e60-e08a276f30f0.png)
![image](https://user-images.githubusercontent.com/79834090/119811457-64a21a00-bee7-11eb-83ee-c94abfd05d9f.png)
![image](https://user-images.githubusercontent.com/79834090/119811256-30c6f480-bee7-11eb-82c9-cbe93584dd67.png)

**Comment by herrstucki** [comment] 2021-05-27 11:21
@ortnever In the latest published version (7) the dimension is indeed not a Key Dimension.

```
_:genid-c8e6cb4357ad4c2faeac08f56f97cadd-6B36A3F683B0873BB0F6C5F922115138 <http://schema.org/name> "Läermbelastete Einheit"@de , "Unité exposé au bruit"@fr , "Unità esposta al rumore"@it , "Unit exposed to noise"@en ;
   <http://www.w3.org/ns/shacl#path> <https://environment.ld.admin.ch/foen/ub001/laermbelasteteeinheit> ;
   <http://www.w3.org/ns/shacl#in> _:genid-c8e6cb4357ad4c2faeac08f56f97cadd-8BA43FE772AB1EB598BF78AF0A9275EE ;
   <http://www.w3.org/ns/shacl#nodeKind> <http://www.w3.org/ns/shacl#IRI> ;
   <http://www.w3.org/ns/shacl#minCount> 1 ;
   <http://www.w3.org/ns/shacl#maxCount> 1 ;
   <http://qudt.org/schema/qudt/scaleType> <http://qudt.org/schema/qudt/NominalScale> ;
   <http://schema.org/version> 7 ;
   <https://cube-creator.zazuko.com/vocab#dimensionMapping> <https://pipelines-integ.lindas.admin.ch/cube-project/testub001-mbbjkbnrab/dimension-mapping/laermbelasteteeinheit-1xkwgowkr7a>
```

Maybe you need to re-publish the cube?

**Comment by ortnever** [comment] 2021-05-27 11:57
I published the cube again (version 8) but it was still the same. I then restarted the transfromation and republished (version 9) but I still have the same problem.
A question: Is it necessary to do the transformation again if you only modify the metadata in the Cube Designer ?

**Comment by herrstucki** [comment] 2021-05-27 12:23
@ortnever yes, I can confirm that in newer versions this dimension is still not marked as KeyDimension.

Ping @l00mi @martinmaillard

**Comment by herrstucki** [comment] 2021-05-27 12:28
To reproduce, run this query: https://s.zazuko.com/ZPbnh (with the correct version number in the cube IRI).

Search for the dimension's name in the output and you'll see that the `a <https://cube.link/KeyDimension> ;` part is missing:

![Bildschirmfoto 2021-05-27 um 14 26 48](https://user-images.githubusercontent.com/70969/119825828-a9ce4800-bef7-11eb-8f63-196da6094c0e.png)

**Comment by tpluscode** [comment] 2021-05-28 07:46
This appears to have been caused by some synchronisation problem in the database cluster. I just published version 10 and it is complete

**Comment by sosiology** [comment] 2022-06-10 13:22
Closing the issue as the previous comment mentions it has been resolved

**Closed by sosiology** 2022-06-10 13:22 UTC
Labels: upstream issue
