### ISSUE TITLE
unexpected error by selecting "Color" (Segmentation)

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#97] opened 2021-06-01 09:06 UTC
Dataset "Bathing Water Quality": I get an unexpected error when I select the dimension "Lieu d'échantillonnage" as Segmentation and "no filter" for the dimension "Monitoring Program".
![image](https://user-images.githubusercontent.com/79834090/120296360-5463b380-c2c8-11eb-90be-389f95e7a0d2.png)
https://test.visualize.admin.ch/en/create/PxC48IT3V9dP

If I select an observation programme in the filter, the display by "Lieu d'échantillonnage" works.
https://test.visualize.admin.ch/en/create/mJAHkdAROTFE
![image](https://user-images.githubusercontent.com/79834090/120296922-e53a8f00-c2c8-11eb-86bf-72ee9d4adcb5.png)

**Comment by ortnever** [comment] 2021-06-01 09:20
It seems to be a problem in the data of following Monitoring Program : GE, SZ, TI, VD

**Comment by ortnever** [comment] 2021-06-01 10:00
For BAQUA_SZ and BAQUA_VD I found for example dates that lost the day information in Visualize. The dates are correct in the Cube Designer and in the original excel file. 

![image](https://user-images.githubusercontent.com/79834090/120304845-6f3a2600-c2d0-11eb-9b06-7ee63533f973.png)
![image](https://user-images.githubusercontent.com/79834090/120304953-87aa4080-c2d0-11eb-96b1-ffc6e6638472.png)

![image](https://user-images.githubusercontent.com/79834090/120305028-97298980-c2d0-11eb-8c35-41e8218bbc4c.png)

For BAQUA_SZ I found a Station Name with a slash /. Could it be a problem? The name is the same in the Data source.

![image](https://user-images.githubusercontent.com/79834090/120305206-c809be80-c2d0-11eb-8dce-557d332895b6.png)

**Comment by herrstucki** [comment] 2021-06-29 08:52
I investigated why this happens, and it is due to the fact that in this dataset some stations have ambiguous names. Also see https://github.com/zazuko/cube-creator/issues/719.

We've added a workaround previously where we would concatenate these names in the dimension metadata (i.e. the metadata we get from the cube's shape). BUT when we query the observations using [rdf-cube-view-query](https://github.com/zazuko/rdf-cube-view-query/) there is no way to do this in the query itself. This has a few implications:

- Observations can show up multiple times, once for each station name, see https://dev.visualize.admin.ch/v/bh5PQZ3dQMdf ([SPARQL query](https://s.zazuko.com/2hjGDP))
- The chart may crash because in some instances the labels are compared – because they differ in the observations and metadata queries, they can't be "found".

This is maybe partly addressable on our end by not relying on comparing labels but the root issue of duplicate observations will still persist unless we change the way we query labels entirely.

- So the solution would be to fix the data (although @l00mi mentioned in https://github.com/zazuko/cube-creator/issues/719 that this may still happen on purpose(?) in the future),
- to work around in our code and de-duplicate observations manually,
- … or to enhance the query library to allow this deduplication in the query itself.

/cc @l00mi @bergos @tpluscode

**Comment by l00mi** [comment] 2021-06-29 09:11
We will discuss this for future cases. For the example at hand, its correct that the customer already confirmed that it is an error in the data?

**Comment by herrstucki** [comment] 2021-06-29 09:12
Yes, in https://github.com/zazuko/cube-creator/issues/719#issuecomment-843913270

**Comment by herrstucki** [comment] 2021-06-29 09:16
I'm marking this issue as "wontfix" for this iteration. We only can address it properly in a future iteration that involves all aspects (data, query library, frontend).

**Comment by tpluscode** [comment] 2021-06-29 09:18
It may be an error in the data this time but duplicate labels is something we should help expect and compensate for IMO.

My take would be to change the query library so that it does two requests. First, a `SELECT` for the measure+dimensions (in this case the **/dateofprobing**, **/parametertype**, **/station** and **/monitotingprogramm**). This is the current query are `?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4`

What appears in the query as `?dimension5` is not in fact a dimension and it is only correct that a Cartesian product is returned. I would extract that as a second `SELECT` to get all labels for the found observations and make it the presentation tool's responsibility to show them and not URLs of concepts. It would be simply the same query, reduced (https://s.zazuko.com/dLYE8) but hey, might also remove all `OPTIONAL` and potential have the UI change language without reloading anything (https://s.zazuko.com/Z9FCq)

**Comment by herrstucki** [comment] 2021-06-29 09:24
@tpluscode Thanks for your input! For reference, a two-pass approach is what you (in the Cube Creator) and we are already doing for querying labels of named nodes described in the shape. Having this directly supported in rdf-cube-view-query would be great for both cases. See https://zulip.zazuko.com/#narrow/stream/40-bafu-ext/topic/visualization.20tool/near/163542

**Comment by ortnever** [comment] 2021-06-29 09:52
Thank you Jeremy for your investigations and everybody for your inputs. 
Regarding our example, as mentioned in my comment, I still had to discuss it with the data provider. It is actually not an error. Only the name of the station has changed. The observation site remains, under a different name, and the continuity of the measurements is assured. We have discussed this case with my colleagues and are of the opinion that there may be other similar examples. Therefore, i agree with Tomasz we should find a solution for these cases.

**Comment by l00mi** [comment] 2021-06-29 09:54
@ortnever I think we all agree, but is it okay that this will take some more investigation and we look into it in more detail with the next project?

In Regards of the observation site which changed, we need to decide:
* Shall the Site have both names, only the early one or only the new one (I would imagine only the new one will be what makes sense?)
* Do we have in the CSV a way to understand that these are the same stations, and when it becomes a new one?

**Comment by ortnever** [comment] 2021-06-29 11:24
Yes, of course. It will be in the next project.

**Comment by herrstucki** [comment] 2021-06-29 11:47
For the record, this is also an issue in the simplified "Gemeindeverzeichnis", where municipalities with the same IRI can have multiple names if they've changed it over time – and no way of knowing which is the most recent one https://s.zazuko.com/jh8E8

**Comment by l00mi** [comment] 2021-06-29 12:22
@herrstucki good catch. That is actually an error there. A community at one point in time has only one name. We have an error here in the creation of the simplified "Gemeindeverzeichnis", @ktk is having a look right now.

**Comment by bergos** [comment] 2021-08-24 12:15
@herrstucki with the new aggregation feature in the view query library, you should be able to generate your label lookup tables with a view like this:

```javascript
const cubeSource = CubeSource.fromSource(source, rdf.namedNode('https://environment.ld.admin.ch/foen/ubd0104bis/10/'))
const lookupSource = LookupSource.fromSource(source)

const labelView = new View({ parent: source })
const stationDimension = labelView.createDimension({
  source: cubeSource,
  path: rdf.namedNode('https://environment.ld.admin.ch/foen/ubd0104bis/station')
})
const labelEnDimension = labelView.createDimension({
  source: lookupSource,
  path: rdf.namedNode('http://schema.org/name'),
  join: stationDimension,
  aggregate: Dimension.aggregate.min
})
const labelEnFilter = labelEnDimension.filter.lang(['en', '', '*'])

labelView
  .addDimension(stationDimension)
  .addDimension(labelEnDimension)
  .addFilter(labelEnFilter)
```

**Closed** 2023-09-07 08:28 UTC
Labels: bug, wontfix, upstream issue
