### ISSUE TITLE
symbol layer is obfuscated by infrastructure and labels

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#537] opened 2022-05-03 14:42 UTC
**Describe the bug**
in maps the symbol layer is below and can become obfuscated by infrastructure.

**To Reproduce**
1. Go to visualize test - > browse
2. Select "Statistik der Wasserkraft..."
3. choose map
4. See resulting map ![image](https://user-images.githubusercontent.com/26090254/166474816-ceb817ee-98d3-4247-a30b-2ecd28919a8e.png)

**Expected behavior**
The symbol layer shall be on top of infra & labels

**Screenshots**
see above

cc @afoletti @zellersabine

**Comment by AFoletti** [comment] 2022-05-04 03:34
Maybe a regression introduced by the "order" fix? See https://github.com/visualize-admin/visualization-tool/issues/479

**Comment by ptbrowne** [comment] 2022-05-04 13:35
Please tell me if it's OK on [test](https://test.visualize.admin.ch/v/hBVlCerruzN0). I could also put the symbol layer above the labels, but a higher zoom levels I think the labels over the symbols is nicer. We could provide a way to show/hide labels generally (currently, we hide labels only if a area layer is shown).

See : https://test.visualize.admin.ch/v/hBVlCerruzN0

cc @AnninaWalker , do you have any input ?

**Comment by Rdataflow** [comment] 2022-05-04 14:39
![image](https://user-images.githubusercontent.com/26090254/166704781-e52a9b2f-f18a-465e-9be0-27231da21d1c.png)
considering the label zurich in this case is less important than the symbol itself, this example makes me favor symbols over labels...

**Comment by AnninaWalker** [comment] 2022-05-04 16:27
Yes there is. I discussed it with Patrick today and we are looking into it

**Comment by ptbrowne** [comment] 2022-05-10 08:07
I think the main issue is fixed since now the symbol layer (circles) are above labels now. So I will close the issue and we shall continue the discussion on a newer issue that will encompass every improvements that we make to the base style (cc @AnninaWalker). Please re open if you see another things.

**Closed** 2022-05-10 08:11 UTC
Labels: bug
