### ISSUE TITLE
PROD : no results when searching with a keyword

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#997] opened 2023-03-07 14:43 UTC
Currently the keyword search does not work on PROD.

- open visualize.admin.ch
- create a visualization
- Enter a keyword for example Modell, bade etc.
- no results

![image](https://user-images.githubusercontent.com/79834090/223455142-9bc4caae-ddcc-433c-a746-50d16d09f7a5.png)

- Visualize environment and version: v3.16
- Browser and version : edge

**Additional context**

**Comment by ptbrowne** [comment] 2023-03-07 15:06
Do you still reproduce the problem ? I cannot reproduce. @l00mi Would you have any idea ?

**Comment by ortnever** [comment] 2023-03-07 15:12
oui juste maintenant, avec Edge, mais c'est instable. parfois ça marche, parfois pas.
je voulais quand même le signaler

![image](https://user-images.githubusercontent.com/79834090/223463797-1c27ceef-13c0-466f-b634-dda7686f7985.png)

**Comment by ortnever** [comment] 2023-03-07 15:32
I noticed the same problem on March 2nd around 9am and I had made a video but 10 minutes later no more problem so I didn't post it 

https://user-images.githubusercontent.com/79834090/223469321-a0e68037-782d-426b-89c6-b92619a155d8.mp4

**Comment by sosiology** [comment] 2023-03-07 18:26
Also could not produce when tested on my device at 19:00. Tested on Chrome, FF, Safari, and Edge on Windows 11 and will retest tomorrow to see if I can reproduce.

**Comment by Rdataflow** [comment] 2023-03-08 16:14
it's even worse today
https://visualize.admin.ch/browse?includeDrafts=false&order=SCORE&search=asdf&dataSource=Prod
returns
![image](https://user-images.githubusercontent.com/26090254/223767459-291a2e11-d15e-4ab2-b1f1-95838d239308.png)

seems upstream is broken 👍

**Comment by l00mi** [comment] 2023-03-08 16:29
On INT pointing to prod it works. https://int.visualize.admin.ch/en/browse?includeDrafts=false&order=SCORE&search=asdf&dataSource=Prod

This would suggest not upstream?

**Comment by Rdataflow** [comment] 2023-03-08 16:32
probably not upstream but dup of https://github.com/visualize-admin/visualization-tool/issues/963

**Comment by Rdataflow** [comment] 2023-03-08 16:33
@ortnever will be fixed with deployment to PROD
cc @zellersabine

**Closed** 2023-05-16 08:15 UTC
Labels: bug, upstream issue, to reproduce
