### ISSUE TITLE
Columns chart + Color/stacked  feature -> Popup is partly out of screen

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#389] opened 2022-02-21 09:26 UTC
**Describe the bug**
In the column chart, when choosing a dimension for the Color option, stacked -> then the values of the stacked data is displayed in a popup.
On my screen, that popup is not entirely visible and we can actually not see the values of the stack elements (see printscreen).

This happens for both: the visualization preparation (screenshot 1), and the final visualization (screenshot 2)

**To Reproduce**
seems straightforward

**Expected behavior**
Show the full popup to the user

**Screenshots**
![image](https://user-images.githubusercontent.com/6167669/154926208-81622721-0673-4b27-bd00-1c8b76046a3e.png)

![image](https://user-images.githubusercontent.com/6167669/154925181-4b595860-22ba-4527-811d-2d8d511de228.png)

**Environment (please complete the following information):**
- Visualize environment and version: TEST v3.4.1 + https://visualize-ad-testingv3--dl6d2r.herokuapp.com/en
- Browser and version: Firefox 97.0.1

**Comment by ptbrowne** [comment] 2022-02-21 09:33
Thanks Fabian for the bug report, this seems like a duplicate of https://github.com/visualize-admin/visualization-tool/issues/315. I am closing this (it will be referenced in the 1st issue).

**Closed by ptbrowne** 2022-02-21 09:33 UTC
Labels: bug

**Comment by FabianCretton** [comment] 2022-02-21 10:34
@ptbrowne I think you can also close this one that seems the same:
https://github.com/visualize-admin/visualization-tool/issues/239

**Comment by ptbrowne** [comment] 2022-02-21 10:55
Thanks @FabianCretton, done 👍

**Comment by AnninaWalker** [comment] 2022-02-24 13:06
@ptbrowne the tooltip is still cut off

**Comment by ptbrowne** [comment] 2022-02-24 13:07
It has been closed in favor of https://github.com/visualize-admin/visualization-tool/issues/315 ;)

**Comment by AnninaWalker** [comment] 2022-02-24 13:08
ah sorry, was just confused because it was still in the internal review lane

**Comment by sosiology** [comment] 2022-03-03 09:23
Saw that this issue has been closed in favor of #315 but just want to make sure this is still on our radar as i noticed sometimes large tooltips are still not fully shown. See: https://int.visualize.admin.ch/en/v/jD9YI6McAdQP

![image](https://user-images.githubusercontent.com/29289679/156535154-7b9a52f7-ea1f-4911-9856-31ba25c0d465.png)

**Comment by ptbrowne** [comment] 2022-03-03 09:25
I am not too sure on how to deal with that as it seems like the root problems is the number of measures that the user has chosen to display. The chart is pathologic here, and am not sure this is the role of the tool to accomodate this usecase. I think here the best would be to show a warning to the user that a large number of things are displayed on the chart and that the user for a better chart should choose less features to be shown.

@AnninaWalker

**Comment by AnninaWalker** [comment] 2022-03-03 09:28
Yes, I guess it would make sense here to show a warning otherwise we would need to add a scrollbar into the tooltip at one point, which would be a bit cumbersome. This could be one of the refinements to tackle in the next sprint

**Comment by ptbrowne** [comment] 2022-03-03 09:39
I think the original issue from Fabian has been deal with so I think we can continue the discussion into [another issue](https://github.com/visualize-admin/visualization-tool/issues/442). Thanks for checking this @sosiology.
