### ISSUE TITLE
all Filters disappear after a filter has been added

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#390] opened 2022-02-21 10:08 UTC
Filters have disappeared after the selection described below. A graph is displayed but filters are no longer specified

**To Reproduce**
1. https://int.visualize.admin.ch/
2. open dataset "Bathing water quality" and start a visualization
3. choose chart type Columns -> next
4. Charts options : add Colors -> select "parameter"
5. Sites : Plage de Gumefens
6. Add Filter "Monitoring programs" 
-> all Filters disappear
-> all data are dispayed in the graphic

https://int.visualize.admin.ch/en/create/0el0xOkJR7bA
![image](https://user-images.githubusercontent.com/79834090/154931319-a0976980-484b-4413-86cd-a81ce44e7cdf.png)

 - Browser and version [e.g. Chrome 95]
INT v3.4.1 ([040ed03]
Microsoft Edge Version 97.0.1072.55 (Version officielle) (64 bits)

**Comment by ptbrowne** [comment] 2022-02-21 11:01
Thanks Véronique, closing as duplicate of #385, we have a solution in #384

**Closed by ptbrowne** 2022-02-21 11:01 UTC
Labels: bug
