### ISSUE TITLE
Search keyword + include dataset

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#721] opened 2022-09-16 08:38 UTC
I thought the problem was solved in # 699 but...If I open int.visualize.admin.ch for the first time, enter a keyword, e.g. "test12" and check the "include draft" box, the keyword disappears and the result shows all drafts (110 results). If I search a second time, with the same or another keyword, for example I enter "emissions" and check the "include draft" box, the keyword is taken into consideration.

- Open int.visualize.admin.ch (if already open, close the application and open it again)
- Search with "test12", check box "include draft"
- result = all draft datasets.

- deselect the "include draft" box
- delete the keyword (with the cross)
- re-enter the keyword or another one
- check the box "include draft"
- result = 1 datset with "test122
-

 - Visualize environment and version: INT v3.8.0 ([9b6863c]
 - Browser and version : Edge

**Comment by ortnever** [comment] 2022-09-16 09:26
The problem does not appear on Firefox 104.0.2.

**Comment by sosiology** [comment] 2022-09-27 13:33
@ortnever I just tested this issue with v3.9.2 on INT and could not reproduce. 
Tested Browsers: Microsoft Edge v105.0.1343.27 on Windows, Chrome on Mac, Safari on Mac. 
As discussed in the weekly call, I will close this issue and we can reopen if it we are able to reproduce the issue reliably.

**Closed by sosiology** 2022-09-27 13:33 UTC
Labels: bug
