### ISSUE TITLE
Alphabetical order is dependent on wheter letters are upper or lowercase

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1052] opened 2023-06-05 13:27 UTC
The title should explain the issue or suggestion almost fully. As most of the time the data set should be uniform for the lettering (capital letters or only lowercase) this is probably only relevant for a few cases. However, I think it is still good to be aware of this, even if we do not need to "fix" this issue.

![Gross-Kleinschreibung-Bug](https://github.com/visualize-admin/visualization-tool/assets/111350367/6454b905-9359-458f-8772-fd91f9e426b6)
[Visualize LFI](https://int.[visualize.admin.ch](https://int.visualize.admin.ch/v/PrMvTnkAiDpc?dataSource=Int)/v/PrMvTnkAiDpc?dataSource=Int)

**Comment by lloydrichards** [comment] 2023-11-07 10:02
Im not able to find the same dataset with this issue, but looking at the image i think the issue is not with ordering, but rather that there is a space between the words "Alphen Sudwest" and not in "Alpensudeite".  I'm going to close this issue for now, but if you can find and sent me a link of this issue, please do so here and I can reopen it

**Closed by lloydrichards** 2023-11-07 10:02 UTC
Labels: enhancement, good first issue
