### ISSUE TITLE
Labelling in hierarchies

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#956] opened 2023-02-06 14:49 UTC
See if https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/437 is possible.

**Comment by sosiology** [comment] 2024-10-24 10:22
Closing this here, as the issue is closed in Gitlab.  The use case is resolved with the parallel hierarchies also see comment here: https://gitlab.ldbar.ch/bafu/visualize/-/issues/437#note_10226

**Closed** 2024-10-24 10:22 UTC
Labels: enhancement
