### ISSUE TITLE
Not able to filter Bathing sites

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#358] opened 2022-02-17 09:43 UTC
**Describe the bug**
In the Bathing site dataset, as soon as I have selected Bathing sites in the Color Segmentation section and try to "Select none" in the Filter section, two weird things happen. In the left side panel, the filters suddenly disappear and in the left side panel I'm not able to select two or three checkboxes. 

**To Reproduce**
1. Go to 'Bathing site dataset'
2. Click on 'Bathing sites' in the Color Segmentation section
3. Click on "Select none" in the filters section
4. Try to select 2 or three checkboxes

**Expected behavior**
I should be able to select only 2 or 3 checkboxes. Filters in the left side panel shouldn't disappear.

**Screenshots**

https://user-images.githubusercontent.com/59613691/154448712-bbb94b69-e3da-4969-9aea-e5f19b9ff297.mov

**Comment by ptbrowne** [comment] 2022-02-17 09:44
Duplicate of https://github.com/visualize-admin/visualization-tool/issues/355, I am on it right now.

**Closed by ptbrowne** 2022-02-17 09:44 UTC
Labels: bug
