### ISSUE TITLE
Problem loading data "Status" for Dataset Red lists

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#510] opened 2022-04-14 16:00 UTC
By Dataset "Red list", when selecting the "Status" dimension as segmentation, the data doesn't load.

1. Go to test.visualize
2. Open the dataset "Red List (latest survey, with %)".
3. Select dimension  "Satus" as "Color" (segmentation).

**Screenshots**
![image](https://user-images.githubusercontent.com/79834090/163428341-95a0eeef-a058-4242-8de6-9575b3b6d2ca.png)

**Environment (please complete the following information):**
 - TEST and version v3.5.0 ([734f063]
 - Browser Edge

**Comment by ptbrowne** [comment] 2022-04-19 09:29
The problem here is that it seems the number of columns in this datasets make the query to fetch the data very slow.

Here is the generated query to copy in https://int.lindas.admin.ch/sparql/.

@l00mi The high number of optional generated by this query seems to be the problem. Would you have any suggestion to make the query faster ? 

```
SELECT ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5 ?dimension6 ?dimension7 ?dimension8 ?dimension9 ?dimension10 ?dimension11 ?dimension12 ?dimension13 ?dimension14 ?dimension15 WHERE {
  <https://environment.ld.admin.ch/foen/ubd003001/9> <https://cube.link/observationSet> ?observationSet0 .
  ?observationSet0 <https://cube.link/observation> ?source0 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/yearissue> ?dimension0 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/value> ?dimension1 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/artengruppe> ?dimension2 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/status> ?dimension3 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/taxon> ?dimension4 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/class> ?dimension5 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/phylum> ?dimension6 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/kingdom> ?dimension7 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd003001/part> ?dimension8 .
  OPTIONAL {
    ?dimension2 <http://schema.org/name> ?dimension9_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension9_0), "en")
    )
  }
  
  BIND(COALESCE(?dimension9_0, ?dimension9_1, ?dimension9_2, ?dimension9_3, ?dimension9_4) AS ?dimension9)
  OPTIONAL {
    ?dimension3 <http://schema.org/name> ?dimension10_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension10_0), "en")
    )
  }
  OPTIONAL {
    ?dimension3 <http://schema.org/name> ?dimension10_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension10_1), "de")
    )
  }
  OPTIONAL {
    ?dimension3 <http://schema.org/name> ?dimension10_2 .
    FILTER (
      LANGMATCHES(LANG(?dimension10_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension3 <http://schema.org/name> ?dimension10_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension10_3), "it")
    )
  }
  OPTIONAL {
    ?dimension3 <http://schema.org/name> ?dimension10_4 .
    FILTER (
      (LANG(?dimension10_4) = "")
    )
  }
  BIND(COALESCE(?dimension10_0, ?dimension10_1, ?dimension10_2, ?dimension10_3, ?dimension10_4) AS ?dimension10)
  OPTIONAL {
    ?dimension4 <http://schema.org/name> ?dimension11_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension11_0), "en")
    )
  }
  OPTIONAL {
    ?dimension4 <http://schema.org/name> ?dimension11_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension11_1), "de")
    )
  }
  OPTIONAL {
    ?dimension4 <http://schema.org/name> ?dimension11_2 .
    FILTER (
      LANGMATCHES(LANG(?dimension11_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension4 <http://schema.org/name> ?dimension11_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension11_3), "it")
    )
  }
  OPTIONAL {
    ?dimension4 <http://schema.org/name> ?dimension11_4 .
    FILTER (
      (LANG(?dimension11_4) = "")
    )
  }
  BIND(COALESCE(?dimension11_0, ?dimension11_1, ?dimension11_2, ?dimension11_3, ?dimension11_4) AS ?dimension11)
  OPTIONAL {
    ?dimension5 <http://schema.org/name> ?dimension12_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension12_0), "en")
    )
  }
  OPTIONAL {
    ?dimension5 <http://schema.org/name> ?dimension12_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension12_1), "de")
    )
  }
  OPTIONAL {
    ?dimension5 <http://schema.org/name> ?dimension12_2 .
    FILTER (
      LANGMATCHES(LANG(?dimension12_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension5 <http://schema.org/name> ?dimension12_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension12_3), "it")
    )
  }
  OPTIONAL {
    ?dimension5 <http://schema.org/name> ?dimension12_4 .
    FILTER (
      (LANG(?dimension12_4) = "")
    )
  }
  BIND(COALESCE(?dimension12_0, ?dimension12_1, ?dimension12_2, ?dimension12_3, ?dimension12_4) AS ?dimension12)
  OPTIONAL {
    ?dimension6 <http://schema.org/name> ?dimension13_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension13_0), "en")
    )
  }
  OPTIONAL {
    ?dimension6 <http://schema.org/name> ?dimension13_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension13_1), "de")
    )
  }
  OPTIONAL {
    ?dimension6 <http://schema.org/name> ?dimension13_2 .
    FILTER (
      LANGMATCHES(LANG(?dimension13_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension6 <http://schema.org/name> ?dimension13_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension13_3), "it")
    )
  }
  OPTIONAL {
    ?dimension6 <http://schema.org/name> ?dimension13_4 .
    FILTER (
      (LANG(?dimension13_4) = "")
    )
  }
  BIND(COALESCE(?dimension13_0, ?dimension13_1, ?dimension13_2, ?dimension13_3, ?dimension13_4) AS ?dimension13)
  OPTIONAL {
    ?dimension7 <http://schema.org/name> ?dimension14_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension14_0), "en")
    )
  }
  OPTIONAL {
    ?dimension7 <http://schema.org/name> ?dimension14_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension14_1), "de")
    )
  }
  OPTIONAL {
    ?dimension7 <http://schema.org/name> ?dimension14_2 .
    FILTER (
      LANGMATCHES(LANG(?dimension14_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension7 <http://schema.org/name> ?dimension14_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension14_3), "it")
    )
  }
  OPTIONAL {
    ?dimension7 <http://schema.org/name> ?dimension14_4 .
    FILTER (
      (LANG(?dimension14_4) = "")
    )
  }
  BIND(COALESCE(?dimension14_0, ?dimension14_1, ?dimension14_2, ?dimension14_3, ?dimension14_4) AS ?dimension14)
  OPTIONAL {
    ?dimension8 <http://schema.org/name> ?dimension15_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension15_0), "en")
    )
  }
  OPTIONAL {
    ?dimension8 <http://schema.org/name> ?dimension15_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension15_1), "de")
    )
  }
  OPTIONAL {
    ?dimension8 <http://schema.org/name> ?dimension15_2 .
    FILTER (
      LANGMATCHES(LANG(?dimension15_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension8 <http://schema.org/name> ?dimension15_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension15_3), "it")
    )
  }
  OPTIONAL {
    ?dimension8 <http://schema.org/name> ?dimension15_4 .
    FILTER (
      (LANG(?dimension15_4) = "")
    )
  }
  BIND(COALESCE(?dimension15_0, ?dimension15_1, ?dimension15_2, ?dimension15_3, ?dimension15_4) AS ?dimension15)
}
```

**Comment by ortnever** [comment] 2022-04-19 13:59
Hi Patrick, 

thanks for your answer. 

you say "The problem here is that it seems the number of columns in this datasets make the query to fetch the data very slow". But 2-3 weeks ago I was able to view the dataset without any problems. Has anything changed since then?

We are currently discussing some improvements for the visualization, with FOEN and Infospecies specialts . It's annoying not to be able to visualise it properly. Should we "re-model" this cube and treat these optional dimensions as hierarchies? Maybe the opportunity to add the aggregated values for kingdoms, phylum etc.

**Comment by ptbrowne** [comment] 2022-04-20 06:27
Hi Veronique, I've asked on the Zazuko chat because I do not think that this is something that we have changed that could cause that. Has the cube changed since 2-3 weeks ago ?

**Comment by ortnever** [comment] 2022-04-29 12:54
Hi Patrick, the cube hasn't changed since February. The cube was re-published on 14 March because one of the csv files was re-imported  with corrected data (same structure, same size). Otherwise there have been no changes so far I know.
@fabiancretton :  do you agree?

**Comment by FabianCretton** [comment] 2022-04-29 13:11
@ptbrowne @ortnever 
Just one thing I have in mind, since 3 weeks, what has change is maybe the Version of Stardog, and I have heard in a meeting this week that some queries were slower, could it be the problem ? @l00mi 
About any change in the data, I do not think so but I will check.

**Comment by FabianCretton** [comment] 2022-04-29 13:17
J'ai donc mis à jour des valeurs dans les fichiers, sans changer la structure, au 15 mars.

**Comment by ortnever** [comment] 2022-05-06 09:19
Dear @ptbrowne and @dmi
I would like this issue to be addressed as a priority. I need a working cube for these red lists as soon as possible. This problem could also occur with other cubes.

Two explanations have been put forward:
- Slow query due to the number of columns -> ok, but then why did the query work until now?
- New version of stardog. Any news from this side?

Fabian tested a simplified query on the endpoint avoiding the labels of the different languages -> the query works.

I made another observation which may be related: Downloading the whole dataset in csv or xls also blocks on cubes, even very small ones, but which include several Concept tables for translations (e.g.: Noise,).

What solutions do you see?

Thanks in advance for your feedback

**Comment by ortnever** [comment] 2022-05-06 09:25
A precision : the download of full dataset "Traffic noise pollution" blocks only on https://test.visualize.admin.ch/. It's ok on int.visualize.admin.ch.

**Comment by ktk** [comment] 2022-05-06 15:10
In what graph is this one? I will dump it and send an issue to Stardog

**Comment by ortnever** [comment] 2022-05-06 16:07
hi @ktk,
if you mean the problem of downloading the full dataset, I don't know if it's important, since it works on the cube in PROD. Maybe it's my cube on Lindas INT that has a problem. It's /foen/ubd0037/5/ on lindas INT.

If you mean my red list query problem, it's the cube foen/ubd003001/9 on Lindas INT. For the query, see Fabian's comment.

**Comment by PDumasBAR** [comment] 2022-05-09 12:58
Hi everyone,
I've made some tests with this cube and I can give you some new information about the data loading problem.
It's possible to load the data when "Status" is selected as the color segmentation by disabling any one "Status".

In the resulting query there is a filter that says:
` FILTER ((?dimension16 IN (<https://environment.ld.admin.ch/foen/ubd003001/Status/DD>, <https://environment.ld.admin.ch/foen/ubd003001/Status/LC>, <https://environment.ld.admin.ch/foen/ubd003001/Status/NT>, <https://environment.ld.admin.ch/foen/ubd003001/Status/VU>, <https://environment.ld.admin.ch/foen/ubd003001/Status/EN>, <https://environment.ld.admin.ch/foen/ubd003001/Status/CR>, <https://environment.ld.admin.ch/foen/ubd003001/Status/RE>))`

With this filter the query is fast. 
But more, the query remains fast if the filter includes all values (I can check that on Lindas, not in visualize):
`FILTER ((?dimension16 IN (<https://environment.ld.admin.ch/foen/ubd003001/Status/DD>, <https://environment.ld.admin.ch/foen/ubd003001/Status/LC>, <https://environment.ld.admin.ch/foen/ubd003001/Status/NT>, <https://environment.ld.admin.ch/foen/ubd003001/Status/VU>, <https://environment.ld.admin.ch/foen/ubd003001/Status/EN>, <https://environment.ld.admin.ch/foen/ubd003001/Status/CR>, <https://environment.ld.admin.ch/foen/ubd003001/Status/RE>, <https://environment.ld.admin.ch/foen/ubd003001/Status/EX>))`

So I think the problem is about some missing values or something like that and the filter excludes those missing values, allowing the query to run faster.

**Comment by ortnever** [comment] 2022-05-09 14:32
The query on the red lists works today and also the download of the full dataset "Traffic Noise Pollution" on Visualize test.
I don't know how the problem was solved as I only look at the discussions on Github but in any case THANK YOU to everyone who was involved :-)

**Comment by ptbrowne** [comment] 2022-05-11 12:33
@ktk @l00mi Do you know what has happened ? We did not do any change on our side.

**Comment by ptbrowne** [comment] 2022-05-11 12:33
I am closing now, please re-open if you see the problem again.

**Comment by l00mi** [comment] 2022-05-16 08:44
@bergos can you check-out https://github.com/visualize-admin/visualization-tool/issues/510#issuecomment-1121067714, would that be something we might use to improve the rdf-cube-view-query lib?

**Comment by ptbrowne** [comment] 2022-05-17 07:21
> @ptbrowne : I don't know how I can re-open the issue..but the same problem occures again.

@ortnever I reopened the issue.

**Comment by ortnever** [comment] 2022-06-09 08:10
for information: I noticed that the stati query was working perfectly on May 30th, but that it was not working anymore on June 7th and it is still the case today (The data can not be loaded).
There was an update from stardog on June 3rd. Is this related?
![image](https://user-images.githubusercontent.com/79834090/172798024-9285ef35-22ff-4e88-8fb5-71551a2ee19a.png)

**Comment by l00mi** [comment] 2022-06-09 08:35
It is definitely not related with the 7th update as this was on TEST which non of the systems of IXT is accessing.

What might be that the additional load on INT still has this effect, but this is pure speculation. @ptbrowne you can confirm that the information is simply not coming back form the store, or is there something more to it?

**Comment by ortnever** [comment] 2022-06-30 07:32
Just for information :
It didn't work on the 7. Juni 2022
It's working today, 30.06.2022 and it worked yesterday.
@ptbrowne : Do you have any idea why it works some days and not others?

**Closed** 2022-09-19 13:17 UTC
Labels: bug, upstream issue
