### ISSUE TITLE
Same columns displayed several times and 2 published versions

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#80] opened 2021-05-11 08:15 UTC
My dataset "Qualité des eaux de baignade" behaves strangely. Two different published versions appear on the left and some attributes are displayed several times. 
![image](https://user-images.githubusercontent.com/79834090/117781986-817cf300-b241-11eb-85e2-986392c9381a.png)
![image](https://user-images.githubusercontent.com/79834090/117782004-8641a700-b241-11eb-8f7f-0954c531ff41.png)

**Comment by herrstucki** [comment] 2021-05-12 07:28
@ortnever This is an error in the data.

- No validThrough is set on the older version, that's why it shows up. [Query](https://s.zazuko.com/2vXstn)
- The dimensions are indeed attached redundantly to the cube. [Query](https://s.zazuko.com/RNj79)

Ping @l00mi @martinmaillard

**Comment by martinmaillard** [comment] 2021-05-12 07:41
Ping @tpluscode

**Comment by l00mi** [comment] 2021-05-12 08:19
@tpluscode can you please just delete the all current cubes, and restart the publication.

**Comment by tpluscode** [comment] 2021-05-13 07:23
Version 6 is in fact broken, apparently caused by running publish twice parallel, which explains why the properties are duplicate on the cube. 

<img width="837" alt="image" src="https://user-images.githubusercontent.com/588128/118091558-3ee72200-b3cb-11eb-9bf0-e7bd475b75e1.png">

We should ensure that two publishing jobs do not run, lest they publish the same cube twice

**Comment by tpluscode** [comment] 2021-05-13 07:24
Second component to this problem is the missing `schema:validThrough`. It appears to be the case when the publishing skips a version number. Such is the case of version 6 and also version 2 but the latter was a draft so it's not being picked up by the UI.

**Comment by tpluscode** [comment] 2021-05-13 10:23
I manually set the expiry of cube versions 2 and 6, so they should not longer appear. The cube-creator PR 715, linked above, will ensure this does not happen again.

Regarding the duplicate publication, I'm not sure it's worth the effort. If it should happen any time, it would be easily fixed by publishing once more. And trying to check for concurrent publish job is not going to be bullet proof anyway

**Closed** 2021-05-17 06:51 UTC
