### ISSUE TITLE
Strange behaviour when sorting by ID on the x-axis

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#978] opened 2023-02-24 11:59 UTC
I add another example related to the issue #976 .
In this example, sorting by ID is correct in the filter but not in the chart. I can't find any logic in the sorting in the chart and strangely it works when using the abbreviations.

- Edit this chart https://int.visualize.admin.ch/en/v/Si4Rjizp0B3n (it takes more than 1 minute until the chart is displayed)
- Edit the horizontal axis
- Select Dimension “BFSIdentifier”
- Select Sort by “Automatic”
- the order of cantons in the chart does not correspond to the ID. Strangely, when abbreviations are used, the sorting is correct. 

![image](https://user-images.githubusercontent.com/79834090/221173460-fb2cc5ad-f842-4219-ade5-7fa8734c7799.png)

![image](https://user-images.githubusercontent.com/79834090/221173503-d410745e-5c6e-426e-9cb2-d6d9ba3b07fe.png)

Environment : Visualize INT, source : INT, v3.19.5 ([0481cfa]
Browser : Edge

**Comment by ptbrowne** [comment] 2023-02-28 15:03
Fixed by https://github.com/visualize-admin/visualization-tool/commit/7eca90ea1260a727aad2fbfb415bd760d3e8b046, it's deploying on int

**Comment by ortnever** [comment] 2023-03-13 09:54
Hi @RdataFlow, the example above works well now on INT but it seems to me that there are some problems by Sorting by ID for Dimension with several parallel levels like Dimension "Region" in Datset  "LFI: Alle Zielgrössen nach Hoch-/Tieflagen".

https://int.visualize.admin.ch/de/v/rOJRafv5qRFd 

Could you have a look to your dataset.  The filter options for the dimension are quite complex.
![image](https://user-images.githubusercontent.com/79834090/224667154-7ea7b67e-efd0-4b60-9b42-9f15464c2e8b.png)

**Comment by Rdataflow** [comment] 2023-03-13 14:42
@ortnever it's really odd.
same here without switzerland https://int.visualize.admin.ch/de/v/w-SsK1P9T1s7 

@ptbrowne can you reopen this issue and fix it?
cc @zellersabine

**Comment by ortnever** [comment] 2023-03-28 11:44
Salut @ptbrowne : Could you also check the sorting by ID (Automatic sorting, by default) at the 2nd hierarchical level (municipalities). I don't understand the logic used. In any case it doesn't seem to be by ID.

**Comment by ptbrowne** [comment] 2023-03-30 12:40
Hi @ortnever and @Rdataflow , I've taken a look, the problem happens when a dimension value is used at two different place in the tree, is this the correct order ?

<img width="539" alt="image" src="https://user-images.githubusercontent.com/465582/228838603-823407d2-54f8-4166-bc3d-c826f23532c8.png">

I need to take a deeper plunge in the code to fix the sorting bug across the charts, but if you can confirm to me that this is the right direction, this would be helpful.

@Rdataflow Could you please when reporting a problem, clearly state what the issue is. it is helpful for me as I am not particularly accustomed to the particular order of each dataset values 😅  (but now I start to get that in the context of wald forest regions, the order should be from north to south , from west to east, according to the topology).

**Closed** 2023-03-31 14:51 UTC
Labels: bug

**Comment by Rdataflow** [comment] 2023-04-04 16:41
@ptbrowne thank you for your work and the first fix. it works great for entities of same place within the hierarchy tree.
However showing canton 'JU' and region 'Jura' those values are combined.

expected:
- [ ] distinct IRIs shall be treated as distinct values:
    <https://ld.admin.ch/canton/26> (canton 'JU') != <https://ld.admin.ch/dimension/bgdi/biota/productionregions/1> (region 'Jura')

- [ ] sort order shall be by (1) hierarchy tree and (2) auto [identifier] resulting in 
    ZH, BE, LU, ...,  Jura, Mittelland, ... , 
    which is basically a flattened view of children tree of `data.dataCubeByIri.dimensions[10].hierarchy`
  ```shell
  curl 'https://int.visualize.admin.ch/api/graphql' -H 'x-visualize-cache-control: no-cache' --data-raw $'{"query":"query DataCubeMetadataWithComponentValues($iri: String\u0021, $sourceType: String\u0021, $sourceUrl: String\u0021, $locale: String\u0021, $latest: Boolean, $filters: Filters) {\\n  dataCubeByIri(\\n    iri: $iri\\n    sourceType: $sourceType\\n    sourceUrl: $sourceUrl\\n    locale: $locale\\n    latest: $latest\\n  ) {\\n    iri\\n    title\\n    publisher\\n    publicationStatus\\n    expires\\n    identifier\\n    workExamples\\n    creator {\\n      iri\\n      __typename\\n    }\\n    landingPage\\n    dimensions(sourceType: $sourceType, sourceUrl: $sourceUrl) {\\n      ...dimensionMetadata\\n      ...hierarchyMetadata\\n      __typename\\n    }\\n    measures(sourceType: $sourceType, sourceUrl: $sourceUrl) {\\n      ...dimensionMetadata\\n      ...hierarchyMetadata\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment dimensionMetadata on Dimension {\\n  iri\\n  label\\n  description\\n  isNumerical\\n  isKeyDimension\\n  dataType\\n  order\\n  values(sourceType: $sourceType, sourceUrl: $sourceUrl, filters: $filters)\\n  unit\\n  related {\\n    iri\\n    type\\n    __typename\\n  }\\n  ...hierarchyMetadata\\n  ... on TemporalDimension {\\n    timeUnit\\n    timeFormat\\n    __typename\\n  }\\n  ... on NumericalMeasure {\\n    isCurrency\\n    currencyExponent\\n    resolution\\n    isDecimal\\n    __typename\\n  }\\n}\\n\\nfragment hierarchyMetadata on Dimension {\\n  hierarchy(sourceType: $sourceType, sourceUrl: $sourceUrl) {\\n    ...hierarchyValueFields\\n    children {\\n      ...hierarchyValueFields\\n      children {\\n        ...hierarchyValueFields\\n        children {\\n          ...hierarchyValueFields\\n          children {\\n            ...hierarchyValueFields\\n            children {\\n              ...hierarchyValueFields\\n              __typename\\n            }\\n            __typename\\n          }\\n          __typename\\n        }\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment hierarchyValueFields on HierarchyValue {\\n  value\\n  dimensionIri\\n  depth\\n  label\\n  alternateName\\n  hasValue\\n  position\\n  identifier\\n}\\n","operationName":"DataCubeMetadataWithComponentValues","variables":{"iri":"https://environment.ld.admin.ch/foen/nfi/C-616/cube/1","sourceType":"sparql","sourceUrl":"https://int.lindas.admin.ch/query","locale":"de"}}' 
  ```

![image](https://user-images.githubusercontent.com/26090254/229853412-516ceb61-3ea4-43e1-bcd2-edd53eb38365.png)
using abbreviation shows the same picture
![image](https://user-images.githubusercontent.com/26090254/229854596-e7777e94-e52a-469c-9c78-929ec2a0fbb0.png)
see also https://int.visualize.admin.ch/v/h8HMMR5YiMbf?dataSource=Int

cc @zellersabine @ortnever @adintegra @sosiology
