### ISSUE TITLE
Published chart popup overlay

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#186] opened 2021-11-02 14:50 UTC
When navigating with the focus tab through the shared links, once the pop up is open, it doesn't close anymore and causes overlays with other popups and buttons

![Screenshot_2020-11-30_at_09 19 15](https://user-images.githubusercontent.com/59613691/139870888-7b772e9e-00c3-4443-96da-1618156442c4.png)

**Comment by ptbrowne** [comment] 2021-11-30 16:20
Cannot reproduce ?

 I tabbed (hit the Tab key on keyboard0 until "Einbetten", did "Enter" (on keyboard) then the popup opened and then I could close it with another Enter, or by clicking anywhere outside the popup.

**Comment by sosiology** [comment] 2022-06-10 09:02
Cannot reproduce in Chrome - suggest closing until it comes up again

**Closed by sosiology** 2022-06-10 09:02 UTC
Labels: bug, popup, to reproduce
