### ISSUE TITLE
BFE published data set not Loading 

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#311] opened 2022-02-02 09:28 UTC
**Describe the bug**
I have just published a new productive LD data set and wanted to display it on visualize.
Unfortunately visualize loads and loads but nothing happens
https://visualize.admin.ch/it/browse/dataset/https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd56_energieperspectives2050%2F1?previous=%7B%22type%22%3A%22organization%22 %2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-energie-bfe%22%2C%22includeDrafts%22%3Afalse%7D
 
I can't really debug because visualize doesn't return any error that I can see and everything worked fine with the cobe-creator
(source: email from Ambrogio Foletti on 01.02.2022)

**To Reproduce**
1. Go to: https://visualize.admin.ch/it/browse/dataset/https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd56_energieperspectives2050%2F1?previous=%7B%22type%22%3A%22organization%22 %2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-energie-bfe%22%2C%22includeDrafts%22%3Afalse%7D
2. Data does not load as expected

**Expected behavior**
The data should load to allow the user to create a visualization

**Screenshots**
![image](https://user-images.githubusercontent.com/29289679/152127190-9c8b3a24-14dc-458d-9164-93b4be8c563e.png)

**Environment (please complete the following information):**
 - Visualize environment and version:PROD
 - Browser and version Chrome

**Additional context**

**Comment by bprusinowski** [comment] 2022-02-02 09:54
Hi @sosiology, a `https://energy.ld.admin.ch/sfoe/bfe_ogd56_energieperspektiven2050/KKWLaufzeit` dimension is a `TemporalDimension`, but does not implement a `timeFormat` property, which should never be empty - that's why the dataset is not being loaded.

**Comment by bprusinowski** [comment] 2022-02-03 10:23
Above was the case for a moment, but it is not anymore. It turned out there is another issue which prevents the data loading - and it's due to a fact that by dimensions with more than 100 values don't have these values attached by default anymore and we have to fetch them in some other way.

I checked and we implemented this on December 11, while the current PROD environment was deployed on December 7 - so this will be fixed once we deploy to PROD (also, it currently works on TEST environment).

Let me know if there is anything else to support with @sosiology.

**Comment by sosiology** [comment] 2022-02-03 15:23
Thanks for the input @bprusinowski. If i understand correctly, we can only fix the issue once we deploy to PROD (whenever that is - tbd) but it should work on TEST if the BFE person wants to try it out. 
I guess my main question is: If Zazuko removes the 100 values limit - would it work on PROD then? if so I would push the issue back to Michael to adjust on their side

**Comment by bprusinowski** [comment] 2022-02-03 16:36
Exactly, once we deploy to PROD it will be fixed - also, currently it works on TEST (just tested).

When it comes to 100 values limit, I am confident that this should be a workaround until we deploy to PROD, as Michael suggested this in the past already.

When I checked the column in question, it has 120 values, so 150 or 200 as a new limit should do fine.

**Comment by sosiology** [comment] 2022-02-04 09:42
Asked the client if it is okay to share the link to the test environment with the user who provided the feedback.

**Comment by sosiology** [comment] 2022-02-04 14:07
Informed user to check / test data set on TEST Environment. If we don't get any feedback in the next week, i will close the issue.

**Comment by AFoletti** [comment] 2022-02-22 11:45
Hello there. BFE Data publisher here. Sorry for the late answer but I was not really aware of this repo.
Anyways, the problem is fixed (checked on INT) and this ticked can in my opinion be closed.

Thanks for your work!

**Comment by ptbrowne** [comment] 2022-02-22 12:36
Thanks @AFoletti !

**Closed by ptbrowne** 2022-02-22 12:36 UTC
Labels: bug

**Comment by AnninaWalker** [comment] 2022-02-24 10:45
LGTM 👍

**Comment by AnninaWalker** [comment] 2022-02-24 10:46
But it takes quite long to load
