### ISSUE TITLE
Getting stuck trying to publish a visualization starting from editing an already existing one

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1379] opened 2024-02-29 09:14 UTC
When trying to publish a visualization after starting from an already published one e.g. [LFI: Themen nach Nadel- und Laubholz](https://int.visualize.admin.ch/de/v/P4XLoaRiDqc4) you get stuck on a screen without proper options to edit, start a new visualization or even share the link to the one you tried to newly publish. 
Publishing works fine when starting from the [preview](https://int.visualize.admin.ch/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-96%2Fcube%2F2023-1&dataSource=Prod)

![publish-bug-20240229](https://github.com/visualize-admin/visualization-tool/assets/111350367/d716d3b0-058e-41bc-9158-fb9956aef7e2)
![publish-bug-2-20240229](https://github.com/visualize-admin/visualization-tool/assets/111350367/1e3f606d-ea43-40be-93f9-1a6aaa0abe5c)

**To Reproduce**

1. Click on the link [LFI: Themen nach Nadel- und Laubholz](https://int.visualize.admin.ch/de/v/P4XLoaRiDqc4)
2. Click on **publish**
4. See error shown in the provided pictures

**Expected behavior**
Being able to publish multiple different visualizations in "one go"

**Environment (please complete the following information):**
- Microsoft Edge Version 120.0.2210.144 (Offizielles Build) (64-Bit)
- Visualize environment and version: [INT v3.26.2 ([a9b1c44](https://github.com/visualize-admin/visualization-tool/commit/a9b1c4426494a0e945afbc3e1a2b696fd35541f6))]

**Comment by tboeni** [comment] 2024-02-29 09:54
This seems to be independent of the visualization type as this also happens for other cubes and diagram options e.g. [Treibhausgasemissionen](https://int.visualize.admin.ch/de/v/-vmhgqyjAO3H)

**Comment by sosiology** [comment] 2024-02-29 11:33
Thanks for reporting @tboeni I was able to reproduce the issue, and we will look into it.
cc: @ptbrowne @bprusinowski

**Comment by ptbrowne** [comment] 2024-02-29 11:34
I suspect this might come from the changes to publication process. I will look into it.

**Comment by Rdataflow** [comment] 2024-03-04 15:41
GQL to reproduce this issue
```sh
curl 'https://int.visualize.admin.ch/api/graphql' -H 'content-type: application/json' -H 'x-visualize-debug: true' --data-raw $'{"query":"query DataCubeObservations($sourceType: String\u0021, $sourceUrl: String\u0021, $locale: String\u0021, $cubeFilter: DataCubeObservationFilter\u0021) {\\n  dataCubeObservations(\\n    sourceType: $sourceType\\n    sourceUrl: $sourceUrl\\n    locale: $locale\\n    cubeFilter: $cubeFilter\\n  )\\n}\\n","operationName":"DataCubeObservations","variables":{"locale":"en","sourceType":"sparql","sourceUrl":"https://lindas.admin.ch/query","cubeFilter":{"iri":"https://environment.ld.admin.ch/foen/ubd000502/4","filters":{"https://environment.ld.admin.ch/foen/ubd000502/gas":{"type":"multi","values":{"https://ld.admin.ch/cube/dimension/pol01air/pol11":true,"https://ld.admin.ch/cube/dimension/pol01air/pol9":true,"https://ld.admin.ch/cube/dimension/pol01air/pol12":true,"https://ld.admin.ch/cube/dimension/pol01air/pol20":true,"https://ld.admin.ch/cube/dimension/pol01air/pol15":true,"https://ld.admin.ch/cube/dimension/pol01air/pol16":true,"https://ld.admin.ch/cube/dimension/pol01air/pol14":true}},"https://environment.ld.admin.ch/foen/ubd000502/jahr":{"type":"single","value":"1990"},"https://environment.ld.admin.ch/foen/ubd000502/sektorid":{"type":"multi","values":{"https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/1":true,"https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/11":true}}}}}}'
 ```

SPARQL to reproduce
```sparql
#pragma describe.strategy cbd
#pragma join.hash off

#pragma describe.strategy cbd
#pragma join.hash off

SELECT DISTINCT ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5 WHERE {
  <https://environment.ld.admin.ch/foen/ubd000502/4> <https://cube.link/observationSet> ?observationSet0 .
  ?observationSet0 <https://cube.link/observation> ?source0 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd000502/sektorid> ?dimension0 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd000502/gas> ?dimension1 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd000502/jahr> ?dimension2 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd000502/werte> ?dimension3 .
  FILTER (
    (?dimension1 IN (<https://ld.admin.ch/cube/dimension/pol01air/pol11>, <https://ld.admin.ch/cube/dimension/pol01air/pol9>, <https://ld.admin.ch/cube/dimension/pol01air/pol20>, <https://ld.admin.ch/cube/dimension/pol01air/pol12>, <https://ld.admin.ch/cube/dimension/pol01air/pol15>, <https://ld.admin.ch/cube/dimension/pol01air/pol16>, <https://ld.admin.ch/cube/dimension/pol01air/pol14>))
  )
  FILTER (
    (?dimension2 = "1990"^^<http://www.w3.org/2001/XMLSchema#gYear>)
  )
  FILTER (
    (?dimension0 IN (<https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/11>, <https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/12>, <https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/13>, <https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/14>))
  )
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension4_0), "en")
    )
  }
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension4_1), "de")
    )
  }
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_2 .
    FILTER (
     LANGMATCHES(LANG(?dimension4_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension4_3), "it")
    )
  }
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_4 .
    FILTER (
      (LANG(?dimension4_4) = "")
    )
  }
  BIND(COALESCE(?dimension4_0, ?dimension4_1, ?dimension4_2, ?dimension4_3, ?dimension4_4) AS ?dimension4)
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension5_0), "en")
    )
  }
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension5_1), "de")
    )
  }
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_2 .
    FILTER (
      LANGMATCHES(LANG(?dimension5_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension5_3), "it")
    )
  }
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_4 .
    FILTER (
      (LANG(?dimension5_4) = "")
    )
  }
  BIND(COALESCE(?dimension5_0, ?dimension5_1, ?dimension5_2, ?dimension5_3, ?dimension5_4) AS ?dimension5)
}
GROUP BY ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5
```
failing with error `com.complexible.stardog.plan.eval.operator.OperatorException: Uncaught error during query evaluation: IllegalArgumentException: Empty union is prohibited`

cc @claudiodigallo

**Comment by Rdataflow** [comment] 2024-03-04 15:44
it works if other filters are applied
```sparql
#pragma describe.strategy cbd
#pragma join.hash off

#pragma describe.strategy cbd
#pragma join.hash off

SELECT DISTINCT ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5 WHERE {
  <https://environment.ld.admin.ch/foen/ubd000502/4> <https://cube.link/observationSet> ?observationSet0 .
  ?observationSet0 <https://cube.link/observation> ?source0 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd000502/sektorid> ?dimension0 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd000502/gas> ?dimension1 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd000502/jahr> ?dimension2 .
  ?source0 <https://environment.ld.admin.ch/foen/ubd000502/werte> ?dimension3 .
  FILTER (
    (?dimension1 IN (<https://ld.admin.ch/cube/dimension/pol01air/pol11>, 
    <https://ld.admin.ch/cube/dimension/pol01air/pol9>#,
#    <https://ld.admin.ch/cube/dimension/pol01air/pol20>, 
#    <https://ld.admin.ch/cube/dimension/pol01air/pol12>, 
#    <https://ld.admin.ch/cube/dimension/pol01air/pol15>, 
#    <https://ld.admin.ch/cube/dimension/pol01air/pol16>, 
#    <https://ld.admin.ch/cube/dimension/pol01air/pol14>
    ))
  )
  FILTER (
    (?dimension2 = "2005"^^<http://www.w3.org/2001/XMLSchema#gYear>)
  )
  FILTER (
    (?dimension0 IN (<https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/11>, <https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/12>, <https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/13>, <https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/14>))
  )
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension4_0), "en")
    )
  }
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension4_1), "de")
    )
  }
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_2 .
    FILTER (
     LANGMATCHES(LANG(?dimension4_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension4_3), "it")
    )
  }
  OPTIONAL {
    ?dimension0 <http://schema.org/name> ?dimension4_4 .
    FILTER (
      (LANG(?dimension4_4) = "")
    )
  }
  BIND(COALESCE(?dimension4_0, ?dimension4_1, ?dimension4_2, ?dimension4_3, ?dimension4_4) AS ?dimension4)
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_0 .
    FILTER (
      LANGMATCHES(LANG(?dimension5_0), "en")
    )
  }
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_1 .
    FILTER (
      LANGMATCHES(LANG(?dimension5_1), "de")
    )
  }
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_2 .
    FILTER (
      LANGMATCHES(LANG(?dimension5_2), "fr")
    )
  }
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_3 .
    FILTER (
      LANGMATCHES(LANG(?dimension5_3), "it")
    )
  }
  OPTIONAL {
    ?dimension1 <http://schema.org/name> ?dimension5_4 .
    FILTER (
      (LANG(?dimension5_4) = "")
    )
  }
  BIND(COALESCE(?dimension5_0, ?dimension5_1, ?dimension5_2, ?dimension5_3, ?dimension5_4) AS ?dimension5)
}
GROUP BY ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5
```
FTR: it seems the set of different filters (gas & sectors) interfere and break the query :(

**Comment by bprusinowski** [comment] 2024-03-07 14:56
@ptbrowne I think this might already be fixed by https://github.com/visualize-admin/visualization-tool/pull/1386 🤞

**Comment by sosiology** [comment] 2024-03-19 16:07
I double checked on int. It seems to be fixed. There is a second where a screen without options is shown but it loads within seconds

**Closed** 2024-08-15 11:57 UTC
Labels: bug
